<script setup lang="ts">
import { computed } from 'vue';
import BaseDateField from '../../components/base/BaseDateField.vue';
import BaseNumberField from '../../components/base/BaseNumberField.vue';
import BaseSelectField from '../../components/base/BaseSelectField.vue';
import BaseSwitchField from '../../components/base/BaseSwitchField.vue';
import BaseTextField from '../../components/base/BaseTextField.vue';
import BaseTextareaField from '../../components/base/BaseTextareaField.vue';
import BaseTimeField from '../../components/base/BaseTimeField.vue';
import FieldGroup from '../../components/base/FieldGroup.vue';
import PlaceholderList from '../../components/base/PlaceholderList.vue';
import { useSenderOptions } from '../../../composables/useSenderOptions';
import { __, textDomain } from '../../../utils/i18n';

const props = defineProps({
  modelValue: { type: Object, default: () => ({}) },
  availablePlaceholders: { type: Array, default: () => [] },
  cronAvailable: { type: Boolean, default: true },
});

const emit = defineEmits(['update:modelValue', 'placeholder-selected']);

const discountTypeOptions = [
  { label: __('Fixed cart discount', textDomain), value: 'fixed_cart' },
  { label: __('Percentage discount', textDomain), value: 'percent' },
];

const expiryTypeOptions = [
  { label: __('Period', textDomain), value: 'period' },
  { label: __('Date', textDomain), value: 'date' },
];

const periodOptions = [
  { label: __('Minutes', textDomain), value: 'minute' },
  { label: __('Hours', textDomain), value: 'hours' },
  { label: __('Days', textDomain), value: 'day' },
  { label: __('Weeks', textDomain), value: 'week' },
  { label: __('Months', textDomain), value: 'month' },
  { label: __('Years', textDomain), value: 'year' },
];

const settings = computed(() => {
  const value = (props.modelValue as Record<string, unknown>).settings;
  return value && typeof value === 'object' ? (value as Record<string, unknown>) : {};
});

const expiry = computed(() => {
  const value = settings.value.expiry_data;
  return value && typeof value === 'object' ? (value as Record<string, unknown>) : {};
});

const message = computed(() => {
  const value = settings.value.message;
  return value && typeof value === 'object' ? (value as Record<string, unknown>) : {};
});

const senderOptions = useSenderOptions(() => message.value.sender);

function updateSettings(patch: Record<string, unknown>) {
  emit('update:modelValue', {
    ...(props.modelValue as Record<string, unknown>),
    settings: { ...settings.value, ...patch },
  });
}

function updateExpiry(patch: Record<string, unknown>) {
  updateSettings({ expiry_data: { ...expiry.value, ...patch } });
}

function updateMessage(patch: Record<string, unknown>) {
  updateSettings({ message: { ...message.value, ...patch } });
}

function insertPlaceholder(placeholder: string) {
  const current = String(message.value.message || '');
  updateMessage({ message: current ? `${current} ${placeholder}` : placeholder });
  emit('placeholder-selected', placeholder);
}
</script>

<template>
  <div class="space-y-4">
    <FieldGroup :title="__('Coupon', textDomain)" :description="__('Configure the WooCommerce coupon generated by this action.', textDomain)">
      <BaseSwitchField
        :model-value="String(settings.generate_coupon || 'yes') === 'yes'"
        :label="__('Generate a unique coupon automatically', textDomain)"
        @update:model-value="updateSettings({ generate_coupon: $event ? 'yes' : 'no' })"
      />
      <BaseTextField
        v-if="String(settings.generate_coupon || 'yes') !== 'yes'"
        :model-value="String(settings.coupon_code || '')"
        :label="__('Coupon code', textDomain)"
        placeholder="SUMMER10"
        @update:model-value="updateSettings({ coupon_code: $event })"
      />
      <BaseTextField
        :model-value="String(settings.coupon_description || '')"
        :label="__('Description', textDomain)"
        :placeholder="__('Internal coupon description', textDomain)"
        @update:model-value="updateSettings({ coupon_description: $event })"
      />
    </FieldGroup>

    <FieldGroup :title="__('Discount', textDomain)">
      <div class="grid gap-4 sm:grid-cols-2">
        <BaseSelectField
          :model-value="String(settings.discount_type || 'fixed_cart')"
          :options="discountTypeOptions"
          :label="__('Discount type', textDomain)"
          @update:model-value="updateSettings({ discount_type: $event })"
        />
        <BaseNumberField
          :model-value="settings.coupon_amount ?? ''"
          :label="__('Amount', textDomain)"
          placeholder="10"
          :min="0"
          @update:model-value="updateSettings({ coupon_amount: $event })"
        />
      </div>
      <BaseSwitchField
        :model-value="String(settings.free_shipping || 'no') === 'yes'"
        :label="__('Allow free shipping', textDomain)"
        @update:model-value="updateSettings({ free_shipping: $event ? 'yes' : 'no' })"
      />
    </FieldGroup>

    <FieldGroup :title="__('Expiration', textDomain)">
      <BaseSwitchField
        :model-value="String(settings.coupon_expiry || 'no') === 'yes'"
        :label="__('Set an expiration', textDomain)"
        @update:model-value="updateSettings({ coupon_expiry: $event ? 'yes' : 'no' })"
      />

      <template v-if="String(settings.coupon_expiry || 'no') === 'yes'">
        <BaseSelectField
          :model-value="String(expiry.type || 'period')"
          :options="expiryTypeOptions"
          :label="__('Expiration mode', textDomain)"
          @update:model-value="updateExpiry({ type: $event })"
        />

        <div v-if="String(expiry.type || 'period') === 'period'" class="grid gap-4 sm:grid-cols-2">
          <BaseNumberField
            :model-value="expiry.delay_value ?? 1"
            :label="__('Amount', textDomain)"
            placeholder="1"
            :min="1"
            @update:model-value="updateExpiry({ delay_value: $event })"
          />
          <BaseSelectField
            :model-value="String(expiry.delay_period || 'day')"
            :options="periodOptions"
            :label="__('Period', textDomain)"
            @update:model-value="updateExpiry({ delay_period: $event })"
          />
        </div>

        <div v-else class="grid gap-4 sm:grid-cols-2">
          <BaseDateField
            :model-value="String(expiry.date_value || '')"
            :label="__('Date', textDomain)"
            @update:model-value="updateExpiry({ date_value: $event })"
          />
          <BaseTimeField
            :model-value="String(expiry.time_value || '')"
            :label="__('Time', textDomain)"
            @update:model-value="updateExpiry({ time_value: $event })"
          />
        </div>
      </template>
    </FieldGroup>

    <FieldGroup :title="__('Coupon message', textDomain)" :description="__('WhatsApp message sent with the generated coupon.', textDomain)">
      <BaseSelectField
        :model-value="String(message.sender || '')"
        :options="senderOptions"
        :label="__('Sender', textDomain)"
        @update:model-value="updateMessage({ sender: $event })"
      />
      <BaseTextField
        :model-value="String(message.receiver || '')"
        :label="__('Recipient', textDomain)"
        :placeholder="__('{{ wc_billing_phone }} or +5511999990000', textDomain)"
        @update:model-value="updateMessage({ receiver: $event })"
      />
      <BaseTextareaField
        :model-value="String(message.message || '')"
        :label="__('Message', textDomain)"
        :rows="5"
        :placeholder="__('Type your message... Use {{ placeholders }} and {{ joinotify_coupon_code }}', textDomain)"
        @update:model-value="updateMessage({ message: $event })"
      />
    </FieldGroup>

    <PlaceholderList
      v-if="Array.isArray(availablePlaceholders) && availablePlaceholders.length"
      :placeholders="availablePlaceholders"
      :title="__('Available placeholders', textDomain)"
      @select="insertPlaceholder"
    />
  </div>
</template>
