<script setup lang="ts">
import { computed } from 'vue';
import BaseDateField from '../../components/base/BaseDateField.vue';
import BaseNumberField from '../../components/base/BaseNumberField.vue';
import BaseSelectField from '../../components/base/BaseSelectField.vue';
import BaseSwitchField from '../../components/base/BaseSwitchField.vue';
import BaseTextField from '../../components/base/BaseTextField.vue';
import BaseTextareaField from '../../components/base/BaseTextareaField.vue';
import BaseTimeField from '../../components/base/BaseTimeField.vue';
import FieldGroup from '../../components/base/FieldGroup.vue';
import PlaceholderList from '../../components/base/PlaceholderList.vue';
import { useWorkflowBuilderStore } from '../../../stores/useWorkflowBuilderStore';

const props = defineProps({
  modelValue: { type: Object, default: () => ({}) },
  availablePlaceholders: { type: Array, default: () => [] },
  cronAvailable: { type: Boolean, default: true },
});

const emit = defineEmits(['update:modelValue', 'placeholder-selected']);

const store = useWorkflowBuilderStore();

const discountTypeOptions = [
  { label: 'Fixed cart discount', value: 'fixed_cart' },
  { label: 'Percentage discount', value: 'percent' },
];

const expiryTypeOptions = [
  { label: 'Period', value: 'period' },
  { label: 'Date', value: 'date' },
];

const periodOptions = [
  { label: 'Minutes', value: 'minute' },
  { label: 'Hours', value: 'hours' },
  { label: 'Days', value: 'day' },
  { label: 'Weeks', value: 'week' },
  { label: 'Months', value: 'month' },
  { label: 'Years', value: 'year' },
];

const settings = computed(() => {
  const value = (props.modelValue as Record<string, unknown>).settings;
  return value && typeof value === 'object' ? (value as Record<string, unknown>) : {};
});

const expiry = computed(() => {
  const value = settings.value.expiry_data;
  return value && typeof value === 'object' ? (value as Record<string, unknown>) : {};
});

const message = computed(() => {
  const value = settings.value.message;
  return value && typeof value === 'object' ? (value as Record<string, unknown>) : {};
});

const senderOptions = computed(() => {
  const senders = Array.isArray(store.bootstrap?.phones?.senders) ? store.bootstrap.phones.senders : [];
  const options = senders
    .map((item: unknown) => String((item && typeof item === 'object' ? (item as Record<string, unknown>).phone : '') || '').trim())
    .filter(Boolean)
    .map((phone: string) => ({ label: phone, value: phone }));

  const current = String(message.value.sender || '').trim();

  if (current && !options.some((option) => option.value === current)) {
    options.unshift({ label: current, value: current });
  }

  return [{ label: '— Select a sender —', value: '' }, ...options];
});

function updateSettings(patch: Record<string, unknown>) {
  emit('update:modelValue', {
    ...(props.modelValue as Record<string, unknown>),
    settings: { ...settings.value, ...patch },
  });
}

function updateExpiry(patch: Record<string, unknown>) {
  updateSettings({ expiry_data: { ...expiry.value, ...patch } });
}

function updateMessage(patch: Record<string, unknown>) {
  updateSettings({ message: { ...message.value, ...patch } });
}

function insertPlaceholder(placeholder: string) {
  const current = String(message.value.message || '');
  updateMessage({ message: current ? `${current} ${placeholder}` : placeholder });
  emit('placeholder-selected', placeholder);
}
</script>

<template>
  <div class="space-y-4">
    <FieldGroup title="Coupon" description="Configure the WooCommerce coupon generated by this action.">
      <BaseSwitchField
        :model-value="String(settings.generate_coupon || 'yes') === 'yes'"
        label="Generate a unique coupon automatically"
        @update:model-value="updateSettings({ generate_coupon: $event ? 'yes' : 'no' })"
      />
      <BaseTextField
        v-if="String(settings.generate_coupon || 'yes') !== 'yes'"
        :model-value="String(settings.coupon_code || '')"
        label="Coupon code"
        placeholder="SUMMER10"
        @update:model-value="updateSettings({ coupon_code: $event })"
      />
      <BaseTextField
        :model-value="String(settings.coupon_description || '')"
        label="Description"
        placeholder="Internal coupon description"
        @update:model-value="updateSettings({ coupon_description: $event })"
      />
    </FieldGroup>

    <FieldGroup title="Discount">
      <div class="grid gap-4 sm:grid-cols-2">
        <BaseSelectField
          :model-value="String(settings.discount_type || 'fixed_cart')"
          :options="discountTypeOptions"
          label="Discount type"
          @update:model-value="updateSettings({ discount_type: $event })"
        />
        <BaseNumberField
          :model-value="settings.coupon_amount ?? ''"
          label="Amount"
          placeholder="10"
          :min="0"
          @update:model-value="updateSettings({ coupon_amount: $event })"
        />
      </div>
      <BaseSwitchField
        :model-value="String(settings.free_shipping || 'no') === 'yes'"
        label="Allow free shipping"
        @update:model-value="updateSettings({ free_shipping: $event ? 'yes' : 'no' })"
      />
    </FieldGroup>

    <FieldGroup title="Expiration">
      <BaseSwitchField
        :model-value="String(settings.coupon_expiry || 'no') === 'yes'"
        label="Set an expiration"
        @update:model-value="updateSettings({ coupon_expiry: $event ? 'yes' : 'no' })"
      />

      <template v-if="String(settings.coupon_expiry || 'no') === 'yes'">
        <BaseSelectField
          :model-value="String(expiry.type || 'period')"
          :options="expiryTypeOptions"
          label="Expiration mode"
          @update:model-value="updateExpiry({ type: $event })"
        />

        <div v-if="String(expiry.type || 'period') === 'period'" class="grid gap-4 sm:grid-cols-2">
          <BaseNumberField
            :model-value="expiry.delay_value ?? 1"
            label="Amount"
            placeholder="1"
            :min="1"
            @update:model-value="updateExpiry({ delay_value: $event })"
          />
          <BaseSelectField
            :model-value="String(expiry.delay_period || 'day')"
            :options="periodOptions"
            label="Period"
            @update:model-value="updateExpiry({ delay_period: $event })"
          />
        </div>

        <div v-else class="grid gap-4 sm:grid-cols-2">
          <BaseDateField
            :model-value="String(expiry.date_value || '')"
            label="Date"
            @update:model-value="updateExpiry({ date_value: $event })"
          />
          <BaseTimeField
            :model-value="String(expiry.time_value || '')"
            label="Time"
            @update:model-value="updateExpiry({ time_value: $event })"
          />
        </div>
      </template>
    </FieldGroup>

    <FieldGroup title="Coupon message" description="WhatsApp message sent with the generated coupon.">
      <BaseSelectField
        :model-value="String(message.sender || '')"
        :options="senderOptions"
        label="Sender"
        @update:model-value="updateMessage({ sender: $event })"
      />
      <BaseTextField
        :model-value="String(message.receiver || '')"
        label="Recipient"
        placeholder="{{ wc_billing_phone }} or +5511999990000"
        @update:model-value="updateMessage({ receiver: $event })"
      />
      <BaseTextareaField
        :model-value="String(message.message || '')"
        label="Message"
        :rows="5"
        placeholder="Type your message... Use {{ placeholders }} and {{ joinotify_coupon_code }}"
        @update:model-value="updateMessage({ message: $event })"
      />
    </FieldGroup>

    <PlaceholderList
      v-if="Array.isArray(availablePlaceholders) && availablePlaceholders.length"
      :placeholders="availablePlaceholders"
      title="Available placeholders"
      @select="insertPlaceholder"
    />
  </div>
</template>
